# Cloud Build configuration for MCP Microservice
# Este archivo define el pipeline de CI/CD para construir y desplegar
# el microservicio MCP en Google Cloud Run

steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ida-microservice:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ida-microservice:latest'
      - '.'
    id: 'build-image'

  # Paso 2: Subir la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ida-microservice:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Paso 3: Subir también la imagen con tag 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ida-microservice:latest'
    id: 'push-latest'
    waitFor: ['build-image']

  # Paso 4: Desplegar a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ida-microservice'
      - '--image=gcr.io/$PROJECT_ID/ida-microservice:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--concurrency=80'
      - '--port=8080'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1,ENV=production,LLM_ENABLED=true'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Configuración de opciones para Cloud Build
options:
  # Usar una máquina con más potencia para builds más rápidos
  machineType: 'E2_HIGHCPU_8'
  
  # Aumentar el timeout para builds complejos
  timeout: '1200s'
  
  # Configurar logging
  logging: CLOUD_LOGGING_ONLY
  
  # Variables de entorno para el build
  env:
    - 'DOCKER_BUILDKIT=1'

# Configuración de substituciones
substitutions:
  # Región por defecto
  _REGION: 'us-central1'
  
  # Nombre del servicio
  _SERVICE_NAME: 'ida-microservice'
  
  # Tag de la imagen (se puede sobreescribir desde la línea de comandos)
  _IMAGE_TAG: 'latest'

# Imágenes a almacenar en Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ida-microservice:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ida-microservice:latest'

# Configuración de artefactos (opcional)
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts'
    paths:
      - 'build-info.json'

# Tags para organizar builds
tags:
  - 'ida-microservice'
  - 'api'
  - 'agents'
  - 'production'